sudo: false
language: node_js
node_js:
- 10
script:
- npm run build
deploy:
  provider: npm
  email: public.sjmallon@gmail.com
  api_key:
    secure: dISaUSw847Khhg0rX9AdXHLmigZpfJpvtmlA/xVOqRkdhQORELeOf1pjuY7mwT5W5uT3DYjWKgsyppny2p3rY7hbwOf0xbyI0wxrivz/jJ6cqVRFi7kGKZF/DwOQ0nG8tkoBejQbOQZyuRBIfpWCfUiMcSM/PmdzElOVBOyzFG8QaLGpabcVKTOg1GAMNCt/XL5S2Ck1yk6d9Tmrjha9XupwgPdFFlBH1smXhE8JVaMpyoHNzz1XmI2ujZ/D73RacvSvcwko840ecdmxP16/rYGyW+m13hlxHUgdSyYnou4slDMvOTPAcv9cpEI4IzfHQuW4EfgYveGoR9WaoNwhH0pNkMdwxtU4f9hLfDTsQONIwPyDNMYsmFz7iOxhAoyOFNlkLGFf8+Z3w2Hrgyaxl7/C8hvE38W90xVeUeumYhY5RaTTBZ+2qMGhbGeZ+2eIxJz8clS4U2PlqU1c4tiqR3mKJhoV4lTUNQwxqqNYTmgVTVCJQUocyoeT2gHKJ7SPblVpKqJbpWwVZihS4mHjNuWeTiu/pkPAuUVxMzEvYYf3f3k+L8sreQoCmMCYicHfgVoU6+aAyjdZYZQwLNfzIeVYexTHofB4/uQxOk/0AD2bDfhlyiBipxbSdJUiztf8OvC/kQJrRVHppyuv9gkXryRy5/zNCL5VhASCN1nsCCg=
  on:
    tags: true
    repo: sjmallon/vue-visjs
